const modes=[["✦","Drawing","Sketch, annotate, and turn rough ideas into something real.","/drawing","coral"],["✎","Sketch","Quickly draw lines, shapes, notes, and ideas on a free canvas.","/drawing/sketch","violet"],["▣","Present","Shape ideas into clear, beautiful slides.","/presentation","violet"],["◫","Teach","Explain, map, and build lessons visually.","/teaching","mint"],["⌁","Machine Building","Explore geometry, dimensions, and simple forms.","/cad","amber"],["✳","AI Lab","Brainstorm, ask, refine, and keep creating.","/ai","blue"]];

export default function Home(){return <div className="shell"><Header/><main className="home">
<section className="intro"><div className="introCopy"><div className="eyebrow"><span/> THE EPIC BUILDERS</div><h1>A little more<br/><em>room to create.</em></h1><p>Doodle Lab is a visual workspace for ideas that don't fit inside one box. Draw something. Teach it. Turn it into slides. Build a shape. Ask AI. Keep the whole creative process together.</p><div className="introActions"><a className="primaryBtn" href="/drawing">Start creating <span>↗</span></a><a className="textBtn" href="/modes">Explore all modes <span>→</span></a></div></div><div className="artPanel"><div className="paper"><div className="paperTop"><span>DOODLE LAB</span><span>01 / 06</span></div><div className="scribble s1"/><div className="scribble s2"/><div className="orbit"/><div className="tinyNote">ideas<br/>become<br/>things.</div><div className="paperFooter">creative workspace <b>✦</b></div></div><div className="floatingTag tagA">draw freely</div><div className="floatingTag tagB">make + learn</div></div></section>

<section className="sectionIntro"><div><div className="eyebrow">YOUR WORKBENCH</div><h2>Six ways to make<br/><em>one idea.</em></h2></div><p>Each mode has a different rhythm. The workspace stays familiar, so you can move from a sketch to a lesson without starting over.</p></section>

<section className="modeGrid">{modes.map(([icon,title,desc,url,accent],i)=><a className={"modeCard "+accent} href={url} key={url}><div className="modeVisual"><span>{icon}</span><small>0{i+1}</small><i/></div><div className="modeInfo"><h3>{title}</h3><p>{desc}</p><b>Open mode <span>↗</span></b></div></a>)}</section>

<section className="studioStrip"><div className="stripMark">✦</div><div><div className="eyebrow">THE IDEA</div><h2>Not another dashboard.</h2><p>A calm, visual place where making is the main thing.</p></div><a href="/projects">See projects <span>→</span></a></section>
</main></div>}
function Header(){return <header className="nav"><a className="brand" href="/"><span className="brandMark">✦</span><span>Doodle <i>Lab</i></span></a><nav className="links"><a className="active" href="/">Home</a><a href="/projects">Projects</a><a href="/modes">Modes</a><a href="/settings">Settings</a></nav><a className="navCta" href="/drawing">Open workspace <span>↗</span></a></header>}