"use client";
import{useEffect,useRef,useState}from"react";
type Tool="straight"|"standing"|"curve"|"sleeping"|"shape";
type Shape="circle"|"square"|"triangle"|"rectangle"|"oval"|"semicircle"|"rhombus"|"parallelogram"|"trapezoid"|"pentagon"|"hexagon"|"heptagon"|"octagon"|"decagon"|"star"|"heart";
const shapes:[Shape,string][]=[["circle","Circle"],["square","Square"],["triangle","Triangle"],["rectangle","Rectangle"],["oval","Oval"],["semicircle","Semicircle"],["rhombus","Rhombus"],["parallelogram","Parallelogram"],["trapezoid","Trapezoid"],["pentagon","Pentagon"],["hexagon","Hexagon"],["heptagon","Heptagon"],["octagon","Octagon"],["decagon","Decagon"],["star","Star"],["heart","Heart"]];
const map:any={circle:"sphere",square:"cube",triangle:"cone",rectangle:"cube",oval:"sphere",semicircle:"sphere",rhombus:"prism",parallelogram:"prism",trapezoid:"prism",pentagon:"prism",hexagon:"prism",heptagon:"prism",octagon:"prism",decagon:"prism",star:"gear",heart:"prism"};
function polygon(g:CanvasRenderingContext2D,x:number,y:number,r:number,n:number){g.beginPath();for(let i=0;i<n;i++){const a=-Math.PI/2+i*Math.PI*2/n,px=x+Math.cos(a)*r,py=y+Math.sin(a)*r;i?g.lineTo(px,py):g.moveTo(px,py)}g.closePath()}
function draw(g:CanvasRenderingContext2D,s:Shape,x:number,y:number){const r=60;g.beginPath();if(s==="circle")g.arc(x,y,r,0,Math.PI*2);else if(s==="square")g.rect(x-60,y-60,120,120);else if(s==="rectangle")g.rect(x-85,y-50,170,100);else if(s==="oval")g.ellipse(x,y,85,50,0,0,Math.PI*2);else if(s==="semicircle"){g.arc(x,y,r,Math.PI,0);g.lineTo(x-r,y)}else if(s==="triangle")polygon(g,x,y,r,3);else if(["pentagon","hexagon","heptagon","octagon","decagon"].includes(s))polygon(g,x,y,r,({pentagon:5,hexagon:6,heptagon:7,octagon:8,decagon:10} as any)[s]);else if(s==="rhombus"){g.moveTo(x,y-r);g.lineTo(x+r,y);g.lineTo(x,y+r);g.lineTo(x-r,y);g.closePath()}else if(s==="parallelogram"){g.moveTo(x-70,y+45);g.lineTo(x+40,y+45);g.lineTo(x+70,y-45);g.lineTo(x-40,y-45);g.closePath()}else if(s==="trapezoid"){g.moveTo(x-70,y+45);g.lineTo(x+70,y+45);g.lineTo(x+45,y-45);g.lineTo(x-45,y-45);g.closePath()}else if(s==="star"){for(let i=0;i<10;i++){const a=-Math.PI/2+i*Math.PI/5,rr=i%2?r:r*.42,px=x+Math.cos(a)*rr,py=y+Math.sin(a)*rr;i?g.lineTo(px,py):g.moveTo(px,py)}g.closePath()}else{g.moveTo(x,y+60);g.bezierCurveTo(x-100,y-5,x-60,y-70,x,y-20);g.bezierCurveTo(x+60,y-70,x+100,y-5,x,y+60)}g.stroke()}
function Model({kind,spin}:{kind:string,spin:boolean}){if(kind==="sphere")return <div className={"sketchModel sphere3d"+(spin?" spin3d":"")}/>;if(kind==="cone")return <div className={"sketchModel cone3d"+(spin?" spin3d":"")}><i/></div>;if(kind==="cylinder")return <div className={"sketchModel cylinder3d"+(spin?" spin3d":"")}><i/></div>;if(kind==="gear")return <div className={"sketchModel gear3d"+(spin?" spin3d":"")}>⚙</div>;if(kind==="prism")return <div className={"sketchModel prism3d"+(spin?" spin3d":"")}><i/></div>;return <div className={"sketchModel cube3d"+(spin?" spin3d":"")}><i/><b/><em/></div>}
export default function CAD(){const[tool,setTool]=useState<Tool>("straight"),[shape,setShape]=useState<Shape>("circle"),[color,setColor]=useState("#20211f"),[size,setSize]=useState(4),[model,setModel]=useState(""),[rotating,setRotating]=useState(true),[saved,setSaved]=useState(""),ref=useRef<HTMLCanvasElement>(null);
useEffect(()=>{const c=ref.current;if(!c)return;const g=c.getContext("2d")!;c.width=1200;c.height=620;g.fillStyle="#fffdf9";g.fillRect(0,0,c.width,c.height);g.strokeStyle="#ded9cf";g.lineWidth=1;for(let x=0;x<1200;x+=40){g.beginPath();g.moveTo(x,0);g.lineTo(x,620);g.stroke()}for(let y=0;y<620;y+=40){g.beginPath();g.moveTo(0,y);g.lineTo(1200,y);g.stroke()}},[]);
const sketch=(e:React.PointerEvent)=>{const c=ref.current!,r=c.getBoundingClientRect(),x=(e.clientX-r.left)*c.width/r.width,y=(e.clientY-r.top)*c.height/r.height,g=c.getContext("2d")!;g.strokeStyle=color;g.lineWidth=size;g.lineCap="round";g.beginPath();if(tool==="straight"||tool==="sleeping"){g.moveTo(x-90,y);g.lineTo(x+90,y)}else if(tool==="standing"){g.moveTo(x,y-90);g.lineTo(x,y+90)}else if(tool==="curve"){g.moveTo(x-90,y);g.bezierCurveTo(x-45,y-80,x+45,y+80,x+90,y)}else{draw(g,shape,x,y);return}g.stroke()};
const convert=()=>setModel(map[shape]||"prism");
const save=()=>{localStorage.setItem("doodle-machine",JSON.stringify({shape,model,rotating,sketch:ref.current?.toDataURL("image/png")}));setSaved("Saved ✓");setTimeout(()=>setSaved(""),1400)};
return <div className="machineApp"><header className="machineTop"><a className="brand" href="/"><span className="brandMark">✦</span><span>Doodle <i>Lab</i></span></a><div className="machineActions"><button onClick={save}>💾 {saved||"Save"}</button><button onClick={()=>setRotating(v=>!v)}>{rotating?"Pause 3D":"Rotate 3D"}</button></div></header><main className="machineMain"><div className="machineIntro"><span className="badge">⌁ Machine Building · Sketch</span><h1>Sketch → 3D.</h1><p>Draw your idea and convert it right here. Nothing leaves Sketch Mode.</p></div><div className="sketchTools"><button className={tool==="straight"?"active":""} onClick={()=>setTool("straight")}>Straight line</button><button className={tool==="standing"?"active":""} onClick={()=>setTool("standing")}>Standing line</button><button className={tool==="curve"?"active":""} onClick={()=>setTool("curve")}>Curved line</button><button className={tool==="sleeping"?"active":""} onClick={()=>setTool("sleeping")}>Sleeping line</button><button className={tool==="shape"?"active":""} onClick={()=>setTool("shape")}>Shape</button><label className="sketchColor">Color <input type="color" value={color} onChange={e=>setColor(e.target.value)}/></label><label className="sketchSize">Size <input type="range" min="2" max="12" value={size} onChange={e=>setSize(+e.target.value)}/></label><select value={shape} onChange={e=>setShape(e.target.value as Shape)}>{shapes.map(([id,n])=><option key={id} value={id}>{n}</option>)}</select><button className="convert3d" onClick={convert}>◆ Convert to 3D</button></div><div className="sketchCanvas"><canvas ref={ref} onPointerDown={sketch}/></div>{model&&<section className="sketch3DResult"><div className="sketch3DHeader"><div><span className="eyebrow">LIVE 3D PREVIEW</span><h2>{model[0].toUpperCase()+model.slice(1)}</h2><p>Your 3D object is displayed here in Sketch Mode.</p></div><button onClick={()=>setModel("")}>Clear 3D</button></div><div className="sketch3DStage"><Model kind={model} spin={rotating}/><span>3D PREVIEW · SKETCH MODE</span></div><div className="sketch3DControls"><button onClick={()=>setRotating(v=>!v)}>{rotating?"Pause rotation":"Auto rotate"}</button><button onClick={save}>＋ Add to Machine Building</button></div></section>}</main></div>}
