"use client";import{useEffect,useRef,useState}from"react";
type Tool="pencil"|"brush"|"eraser";type Stroke={tool:Tool;color:string;size:number;points:{x:number;y:number}[]};type Label={text:string;color:string;x:number;y:number};
export default function Drawing(){const canvas=useRef<HTMLCanvasElement>(null);const[color,setColor]=useState("#20211f");const[size,setSize]=useState(6);const[tool,setTool]=useState<Tool>("pencil");const[text,setText]=useState("");const[strokes,setStrokes]=useState<Stroke[]>([]);const[labels,setLabels]=useState<Label[]>([]);const[current,setCurrent]=useState<{x:number;y:number}[]>([]);const[down,setDown]=useState(false);
useEffect(()=>{render()},[strokes,current,down,labels]);
const pos=(e:React.PointerEvent)=>{const c=canvas.current!,r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*c.width/r.width,y:(e.clientY-r.top)*c.height/r.height}};
const render=()=>{const c=canvas.current;if(!c)return;const g=c.getContext("2d")!;g.fillStyle="#fffdf9";g.fillRect(0,0,c.width,c.height);const all=[...strokes,...(current.length?[{tool,color,size,points:current}]:[])];for(const s of all){g.strokeStyle=s.tool==="eraser"?"#fffdf9":s.color;g.lineWidth=s.tool==="brush"?s.size*2:s.size;g.lineCap="round";g.lineJoin="round";g.beginPath();s.points.forEach((p,i)=>i?g.lineTo(p.x,p.y):g.moveTo(p.x,p.y));g.stroke()}g.fillStyle=color;g.font="700 30px sans-serif";labels.forEach(l=>g.fillText(l.text,l.x,l.y))};
const start=(e:React.PointerEvent)=>{const p=pos(e);setDown(true);setCurrent([p])};const move=(e:React.PointerEvent)=>{if(!down)return;setCurrent(v=>[...v,pos(e)])};const end=()=>{if(!down)return;setDown(false);if(current.length)setStrokes(v=>[...v,{tool,color,size,points:current}]);setCurrent([])};
const addText=()=>{const value=text.trim();if(!value)return;setLabels(v=>[...v,{text:value,color,x:80,y:90+v.length*38}]);setText("")};const clear=()=>{setStrokes([]);setLabels([])};const saveFile=()=>{const files=JSON.parse(localStorage.getItem("doodle-files")||"[]");files.unshift({id:Date.now().toString(),mode:"Drawing",title:"Drawing",data:canvas.current?.toDataURL("image/png")||""});localStorage.setItem("doodle-files",JSON.stringify(files.slice(0,50)))};
return <div className="shell"><Header/><main className="workspace"><div className="workspaceHead"><div><span className="badge">🎨 Drawing Mode</span><h1>Make something.</h1><p>Draw, add text, and build ideas on one canvas.</p></div></div><div className="drawingTools"><div className="toolGroup"><button className={tool==="pencil"?"tool active":"tool"} onClick={()=>setTool("pencil")}>✏️ Pencil</button><button className={tool==="brush"?"tool active":"tool"} onClick={()=>setTool("brush")}>🖌️ Brush</button><button className={tool==="eraser"?"tool active":"tool"} onClick={()=>setTool("eraser")}>⌫ Eraser</button></div><div className="toolGroup textGroup"><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>e.key==="Enter"&&addText()} placeholder="Type text..."/><button className="tool" onClick={addText}>T Add text</button></div><div className="toolGroup"><label className="tool">🎨 <input aria-label="Color" type="color" value={color} onChange={e=>setColor(e.target.value)}/></label><label className="sizeControl">Size <input type="range" min="1" max="40" value={size} onChange={e=>setSize(+e.target.value)}/></label><button className="tool" onClick={saveFile}>📁 Save to File</button><button className="tool" onClick={clear}>Clear</button></div></div><div className="canvasWrap"><canvas ref={canvas} width={1400} height={760} className="canvas" onPointerDown={start} onPointerMove={move} onPointerUp={end} onPointerCancel={end} onPointerLeave={()=>down&&end()}/></div></main></div>}
function Header(){return <header className="nav"><a className="brand" href="/"><span className="brandMark">✦</span><span>Doodle <i>Lab</i></span></a><nav className="links"><a href="/">Home</a><a href="/projects">Projects</a><a href="/modes">Modes</a><a href="/settings">Settings</a></nav><a className="navCta" href="/drawing">Drawing</a></header>}