"use client";
import{useEffect,useRef,useState}from"react";
type Tool="pencil"|"brush"|"fill"|"eraser";
export default function Drawing(){
 const ref=useRef<HTMLCanvasElement>(null); const[color,setColor]=useState("#20211f"); const[size,setSize]=useState(6); const[tool,setTool]=useState<Tool>("pencil"); const[down,setDown]=useState(false); const[media,setMedia]=useState<{type:"image"|"video";url:string}[]>([]); const[ai,setAi]=useState(""); const[text,setText]=useState("");
 useEffect(()=>{const c=ref.current!;c.width=1200;c.height=650;const x=c.getContext("2d")!;x.fillStyle="#fffdf9";x.fillRect(0,0,c.width,c.height)},[]);
 const point=(e:React.PointerEvent)=>{const c=ref.current!,r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*c.width/r.width,y:(e.clientY-r.top)*c.height/r.height}};
 const flood=(sx:number,sy:number)=>{const c=ref.current!,x=c.getContext("2d")!,w=c.width,h=c.height;const img=x.getImageData(0,0,w,h),d=img.data,i=(Math.floor(sy)*w+Math.floor(sx))*4,target=[d[i],d[i+1],d[i+2],d[i+3]],fill=[parseInt(color.slice(1,3),16),parseInt(color.slice(3,5),16),parseInt(color.slice(5,7),16),255];if(target.every((v,j)=>v===fill[j]))return;const q:[[number,number]]= [[Math.floor(sx),Math.floor(sy)]] as any;while(q.length){const[p]=q.splice(0,1),px=p[0],py=p[1];if(px<0||py<0||px>=w||py>=h)continue;const k=(py*w+px)*4;if(d[k]!==target[0]||d[k+1]!==target[1]||d[k+2]!==target[2]||d[k+3]!==target[3])continue;d[k]=fill[0];d[k+1]=fill[1];d[k+2]=fill[2];d[k+3]=fill[3];q.push([px+1,py],[px-1,py],[px,py+1],[px,py-1]);}x.putImageData(img,0,0)};
 const start=(e:React.PointerEvent)=>{const p=point(e);if(tool==="fill"){flood(p.x,p.y);return}const x=ref.current!.getContext("2d")!;x.beginPath();x.moveTo(p.x,p.y);setDown(true)};
 const draw=(e:React.PointerEvent)=>{if(!down||tool==="fill")return;const p=point(e),x=ref.current!.getContext("2d")!;x.strokeStyle=tool==="eraser"?"#fffdf9":color;x.lineWidth=tool==="brush"?size*2:size;x.lineCap="round";x.lineTo(p.x,p.y);x.stroke();x.beginPath();x.moveTo(p.x,p.y)};
 const clear=()=>{const c=ref.current!,x=c.getContext("2d")!;x.clearRect(0,0,c.width,c.height);x.fillStyle="#fffdf9";x.fillRect(0,0,c.width,c.height)};
 const addMedia=(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(f)setMedia(v=>[...v,{type:f.type.startsWith("video")?"video":"image",url:URL.createObjectURL(f)}])};
 return <div className="shell"><Header/><main className="workspace"><div className="workspaceHead"><div><span className="badge">🎨 Drawing Mode</span><h1>Make something.</h1><p>A flexible canvas for sketching, painting, media, and ideas.</p></div><button className="aiTool" onClick={()=>setAi("AI is ready to help brainstorm, label, or refine your canvas.")}>🤖 AI</button></div>
 <div className="drawingTools"><div className="toolGroup"><input className="textToolInput" value={text} onChange={e=>setText(e.target.value)} placeholder="Add text"/><button className="tool" onClick={()=>{if(text.trim()){const c=ref.current!,x=c.getContext("2d")!;x.fillStyle=color;x.font="bold 28px sans-serif";x.fillText(text,80,90);setText("")}}}>T Text</button></div><div className="toolGroup">{([["pencil","✏️","Pencil"],["brush","🖌️","Brush"],["fill","🪣","Fill"],["eraser","⌫","Eraser"]] as const).map(([id,icon,name])=><button className={tool===id?"tool active":"tool"} onClick={()=>setTool(id)} key={id}>{icon}<span>{name}</span></button>)}</div><div className="toolGroup"><label className="tool">🎨<input aria-label="Color" type="color" value={color} onChange={e=>setColor(e.target.value)}/></label><label className="sizeControl">Size <input type="range" min="1" max="40" value={size} onChange={e=>setSize(+e.target.value)}/></label><label className="tool">🖼️ Photo<input hidden type="file" accept="image/*" onChange={addMedia}/></label><label className="tool">🎥 Video<input hidden type="file" accept="video/*" onChange={addMedia}/></label><button className="tool" onClick={clear}>Clear</button></div></div>
 {ai&&<div className="aiNotice">{ai}</div>}<div className="canvasWrap"><canvas ref={ref} className="canvas" onPointerDown={start} onPointerUp={()=>setDown(false)} onPointerLeave={()=>setDown(false)} onPointerMove={draw}/></div>
 {media.length>0&&<div className="mediaTray">{media.map((m,i)=>m.type==="image"?<img key={i} src={m.url} alt="Added media"/>:<video key={i} src={m.url} controls/> )}</div>}</main></div>}
function Header(){return <header className="nav"><a className="brand" href="/"><span className="brandMark">✦</span><span>Doodle <i>Lab</i></span></a><nav className="links"><a href="/">Home</a><a href="/projects">Projects</a><a href="/modes">Modes</a><a href="/settings">Settings</a></nav><a className="navCta" href="/drawing">Drawing</a></header>}